# Lesson 5
Now that we have covered some basics, we can have a look a the true power of Python. In this lesson, I want to cover the most widely used libraries in science/economics.

The libraries I want to cover are:

1. Numpy
2. Pandas
3. Scipy

Since those libraries are huge, I just want to provide an illustration of what they can be used for.

Assuming you have already installed the required library (e.g. via pip), all that we have to do to use a library is to import it.

### Numpy: Efficient library for linear algebra

In [6]:
# Import numpy and abbreviate it as np
import numpy as np

# Create array (aka matrix) of ones
A = np.array([[1, 2], [3, 4]]) # Note that we are passing in a list of lists!
print(A)

[[1 2]
 [3 4]]


In [17]:
# Slicing arrays works similar to slicing lists
# Grab first column
print(A[:, 0]) # Don't forget that Python uses zero-based indexing!

[1 3]
[1 2]


In [18]:
# Grab first row
print(A[0, :])

[1 2]


In [27]:
# Multiplication
B = np.eye(2)

C = A * B # Note that this syntax will perform element-wise multiplication.
C

array([[1., 0.],
       [0., 4.]])

In [29]:
C = np.dot(A, B) # np.dot() will perform matrix multiplication.
C

array([[1., 2.],
       [3., 4.]])

In [37]:
# Transpose and inverse
At = A.transpose()
print('Transpose of matrix A:\n', At)

# Inverse
Ai = np.linalg.inv(A)
print('Inverse of matrix A:\n', Ai)

Transpose of matrix A:
 [[1 3]
 [2 4]]
Inverse of matrix A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


As mentioned before, `numpy` is a big and widely used library. For more information, check out the `numpy` homepage: https://numpy.org/

### Pandas
`pandas` is a Python library for data analysis. According to its website, `pandas` is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of the Python programming language.

For more information see: https://pandas.pydata.org/

In [17]:
# Let's import the pandas library. The convention is to abbreviate it as 'pd'
import pandas as pd

# The basic data type in pandas is a pd.Series, which you can think of as a column of your data
# Let's create a random pd.Series using numpy
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])
print(s)

a   -2.911418
b   -0.580940
c   -1.613089
d    0.120474
e    1.620019
dtype: float64


In [18]:
index = pd.date_range("1/1/2000", periods=8)
df = pd.DataFrame(np.random.randn(8, 3), index=index, columns=["A", "B", "C"])

df.head()

A         B         C
2000-01-01  0.937446 -0.945522  0.068747
2000-01-02 -0.288827  0.563346  1.394054
2000-01-03  1.210287  1.920864  0.369189
2000-01-04  0.923030  0.178153 -0.266281
2000-01-05  0.356966 -0.797334 -0.077179

a    0.061811
b   -0.616316
c   -1.912763
d    0.450811
e    0.162389
dtype: float64

In [ ]:
# We want to import only one function from fastquant
from fastquant import get_stock_data

# Grab data on a particular stock
df = get_stock_data('GME', '2018-01-01', '2019-01-01')