# Lesson 5
Now that we have covered some basics, we can have a look a the true power of Python. In this lesson, I want to cover the most widely used libraries in science/economics.

The libraries I want to cover are:

1. Numpy
2. Pandas
3. Scipy

Since those libraries are huge, I just want to provide an illustration of what they can be used for.

Assuming you have already installed the required library (e.g. via pip), all that we have to do to use a library is to import it.

### Numpy: Efficient library for linear algebra

In [14]:
# Import numpy and abbreviate it as np
import numpy as np

# Create array (aka matrix) of ones
A = np.array([[1, 2], [3, 4]]) # Note that we are passing in a list of lists!
print(A)

[[1 2]
 [3 4]]


In [17]:
# Slicing arrays works similar to slicing lists
# Grab first column
print(A[:, 0]) # Don't forget that Python uses zero-based indexing!

[1 3]
[1 2]


In [18]:
# Grab first row
print(A[0, :])

[1 2]


In [27]:
# Multiplication
B = np.eye(2)

C = A * B # Note that this syntax will perform element-wise multiplication.
C

array([[1., 0.],
       [0., 4.]])

In [29]:
C = np.dot(A, B) # np.dot() will perform matrix multiplication.
C

array([[1., 2.],
       [3., 4.]])

In [37]:
# Transpose and inverse
At = A.transpose()
print('Transpose of matrix A:\n', At)

# Inverse
Ai = np.linalg.inv(A)
print('Inverse of matrix A:\n', Ai)

Transpose of matrix A:
 [[1 3]
 [2 4]]
Inverse of matrix A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


As mentioned before, `numpy` is a big and widely used library. For more information, check out the `numpy` homepage: https://numpy.org/